### ISSUE TITLE
Schiffbruch fails to link with SFML

### ISSUE THREAD

**Issue by FSMaxB** [eXpl0it3r/Schiffbruch#2]
I've tried with VS2015 and 2017 on Windows 7 and Windows 10 and I don't seem to get Schiffbruch compiled.

Well actually it compiles, but the linker complains, see the attached logfile.

[build.txt](https://github.com/eXpl0it3r/Schiffbruch/files/1101388/build.txt)

**Comment by eXpl0it3r** [comment]
You need to build SFML with the SFML_USE_STATIC_STD_LIBS flag set in CMake. That way SFML will be built with the MT / MTd flag.

Alternatively you can change the project settings to use MD / MDd flags.

**Comment by FSMaxB** [comment]
Thanks, manually building SFML with SFML_USE_STATIC_STD_LIBS worked. Now I can continue working on the JSON export.

**Comment by eXpl0it3r** [comment]
Nice! Keep me posted! 😊
